import { useContext, useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import type { ShoppingItem } from '@coocoo/contracts'
import { UiContext } from '@/app/ui-context'
import { Modal, ModalHeader } from '@/shared/ui/Modal'
import { api, json } from '@/shared/api/client'
import { stateQueryKey } from '@/entities/app-state/model'

export function AddShoppingModal({onClose,item}:{onClose:()=>void;item?:ShoppingItem}){const ui=useContext(UiContext);const query=useQueryClient();return <Modal label="新增待採買食材" onClose={onClose}><ModalHeader title={item?'編輯待採買食材':'新增待採買食材'} onClose={onClose}/><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const value={name:String(f.get('name')),category:String(f.get('category')),qty:Number(f.get('qty')),unit:String(f.get('unit')),estCost:Number(f.get('estCost')),checked:item?.checked||false,status:item?.status||'手動新增'};await api(item?`/shopping-items/${item.id}`:'/shopping-items',json(item?'PATCH':'POST',value));await query.invalidateQueries({queryKey:stateQueryKey});onClose();ui.toast(item?'採買項目已更新':'食材已加入採買清單')}} className="grid grid-cols-2 gap-md"><label className="col-span-2 text-xs font-bold text-on-surface-variant">食材名稱<input className="field" name="name" defaultValue={item?.name} required/></label><label className="text-xs font-bold text-on-surface-variant">分類<select className="field" name="category" defaultValue={item?.category||'produce'}><option value="produce">新鮮蔬果</option><option value="protein">蛋白質與乳製品</option></select></label><label className="text-xs font-bold text-on-surface-variant">數量<input className="field" type="number" name="qty" defaultValue={item?.qty||1}/></label><label className="text-xs font-bold text-on-surface-variant">單位<input className="field" name="unit" defaultValue={item?.unit||'包'}/></label><label className="text-xs font-bold text-on-surface-variant">預估金額<input className="field" type="number" name="estCost" defaultValue={item?.estCost||50}/></label><button className="primary-btn col-span-2 mt-md">確認{item?'更新':'加入'}</button></form></Modal>}

export function VoiceInputModal({onClose}:{onClose:()=>void}){const [text,setText]=useState('雞蛋兩盒、番茄3顆');const [parsed,setParsed]=useState<ShoppingItem[]>([]);const query=useQueryClient();const ui=useContext(UiContext);const parse=async()=>setParsed(await api('/shopping/parse',json('POST',{text})));const add=async()=>{for(const item of parsed)await api('/shopping-items',json('POST',item));await query.invalidateQueries({queryKey:stateQueryKey});onClose();ui.toast(`已匯入 ${parsed.length} 項食材`)};return <Modal label="語音輸入採買" onClose={onClose}><ModalHeader title="用說的建立採買單" onClose={onClose}/><div className="voice-wave-container mb-md text-center"><span className="material-symbols-outlined text-5xl text-primary">mic</span></div><textarea value={text} onChange={e=>setText(e.target.value)} className="field min-h-24"/><button onClick={parse} className="secondary-btn mt-md w-full">解析內容</button>{parsed.length>0&&<div className="mt-md space-y-xs">{parsed.map(item=><div key={item.id} className="rounded-xl bg-surface-container-low p-sm text-xs"><strong>{item.name}</strong> · {item.qty}{item.unit}</div>)}<button onClick={add} className="primary-btn mt-sm w-full">匯入勾選項目</button></div>}</Modal>}

const invoice=[{name:'青江菜',category:'produce',qty:1,unit:'包',estCost:45},{name:'雞胸肉',category:'protein',qty:2,unit:'盒',estCost:178},{name:'牛番茄',category:'produce',qty:4,unit:'顆',estCost:120}]
export function InvoiceModal({onClose}:{onClose:()=>void}){const query=useQueryClient();const ui=useContext(UiContext);const add=async()=>{for(const item of invoice)await api('/shopping-items',json('POST',{...item,checked:false,status:'發票掃描'}));await query.invalidateQueries({queryKey:stateQueryKey});onClose();ui.toast('發票品項已加入採買清單')};return <Modal label="掃描發票" onClose={onClose}><ModalHeader title="發票掃描結果" kicker="模擬辨識" onClose={onClose}/><div className="relative overflow-hidden rounded-2xl bg-slate-blue p-lg text-white"><div className="animate-scan-line"/>{invoice.map(item=><div key={item.name} className="flex justify-between border-b border-white/10 py-sm text-xs"><span>{item.name}</span><strong>NT$ {item.estCost}</strong></div>)}</div><button onClick={add} className="primary-btn mt-lg w-full">匯入選取品項</button></Modal>}

export function ShoppingAssistantModal({onClose}:{onClose:()=>void}){const [result,setResult]=useState<{summary:string;recommendations:ShoppingItem[]}|null>(null);return <Modal label="AI 陪我逛" onClose={onClose}><ModalHeader title="AI 陪我逛" kicker="採買決策助手" onClose={onClose}/><p className="rounded-2xl bg-surface-container-low p-md text-xs leading-5 text-on-surface-variant">可以先從冰箱與本週餐數出發，避免只因折扣買進用不完的份量。</p><button onClick={async()=>setResult(await api('/shopping/analyze',json('POST',{})))} className="primary-btn mt-md w-full">分析目前採買單</button>{result&&<div className="mt-md rounded-2xl border border-secondary/20 bg-secondary/10 p-md"><strong className="text-sm text-secondary">{result.summary}</strong><ul className="mt-sm list-inside list-disc text-xs text-on-surface-variant">{result.recommendations.map(i=><li key={i.id}>{i.name} · NT$ {i.estCost}</li>)}</ul></div>}</Modal>}
