/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './app.js', './src/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#9a442d',
        'on-primary': '#ffffff',
        'primary-container': '#e07a5f',
        'on-primary-container': '#5b1604',
        secondary: '#386753',
        'on-secondary': '#ffffff',
        'secondary-container': '#b8ebd1',
        'on-secondary-container': '#3d6c57',
        tertiary: '#765a28',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b3915a',
        'on-tertiary-container': '#402b00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fdfae7',
        surface: '#fdfae7',
        'surface-dim': '#dddbc8',
        'surface-bright': '#fdfae7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f4e1',
        'surface-container': '#f1eedb',
        'surface-container-high': '#ece9d6',
        'surface-container-highest': '#e6e3d0',
        'on-surface': '#1c1c11',
        'on-surface-variant': '#55423e',
        outline: '#88726d',
        'outline-variant': '#dbc1ba',
        terracotta: '#e07a5f',
        'sage-green': '#81b29a',
        'ochre-gold': '#f2cc8f',
        'slate-blue': '#3d405b',
        'rust-orange': '#d95d39',
        'oatmeal-sand': '#f4f1de',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        full: '9999px',
      },
      spacing: {
        4.5: '18px',
        gutter: '20px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        'container-max': '1200px',
      },
    },
  },
};
