import { useContext, useEffect, useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import type { Recipe } from '@coocoo/contracts'
import { api, json } from '@/shared/api/client'
import { Modal, ModalHeader } from '@/shared/ui/Modal'
import { UiContext } from '@/app/ui-context'
import { useAppState, stateQueryKey } from '@/entities/app-state/model'

export function RecipeModal({ingredientIds,style,onClose,onComplete}:{ingredientIds:string[];style:string;onClose:()=>void;onComplete?:()=>void}){const [recipe,setRecipe]=useState<Recipe|null>(null);const [error,setError]=useState('');const ui=useContext(UiContext);useEffect(()=>{api<Recipe>('/recipes/generate',json('POST',{ingredientIds,style})).then(setRecipe).catch(e=>setError(e.message))},[ingredientIds,style]);if(error)return <Modal label="食譜產生失敗" onClose={onClose}><ModalHeader title="食譜產生失敗" onClose={onClose}/><p className="rounded-xl bg-error-container p-md text-xs text-on-error-container">{error}</p></Modal>;if(!recipe)return <Modal label="AI 備菜中" onClose={onClose}><div className="py-xl text-center"><span className="material-symbols-outlined animate-pulse text-5xl text-secondary">auto_awesome</span><h3 className="mt-md font-extrabold text-slate-blue">AI 正在整理一鍋料理</h3></div></Modal>;return <Modal label={recipe.title} onClose={onClose} wide><ModalHeader title={recipe.title} kicker={`${recipe.style} · ${recipe.prepTime} · ${recipe.estCost}`} onClose={onClose}/><div className="rounded-2xl bg-secondary/10 p-md"><strong className="text-xs text-secondary">科學自煮物理原理</strong><p className="mt-1 text-xs leading-5 text-on-surface-variant">{recipe.scientificPrinciple}</p></div><ol className="mt-md space-y-sm">{recipe.steps.map((step,index)=><li key={step} className="flex gap-sm rounded-2xl bg-surface-container-low p-md"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary text-xs font-extrabold text-white">{index+1}</span><p className="text-sm leading-6 text-slate-blue">{step}</p></li>)}</ol><div className="mt-lg flex flex-col gap-sm sm:flex-row"><button onClick={async()=>setRecipe(await api('/recipes/generate',json('POST',{ingredientIds,style,excludeTitle:recipe.title})))} className="secondary-btn flex-1">換一道</button><button onClick={()=>ui.open(<CookingCompleteModal recipe={recipe} ingredientIds={ingredientIds} onClose={onClose} onComplete={onComplete}/>)} className="primary-btn flex-1">完成自煮開飯</button></div></Modal>}

function CookingCompleteModal({recipe,ingredientIds,onClose,onComplete}:{recipe:Recipe;ingredientIds:string[];onClose:()=>void;onComplete?:()=>void}){const {data}=useAppState();const query=useQueryClient();const ui=useContext(UiContext);const estimate=data?.cookingPlan?.estimatedSavingPerMeal||0;const [cost,setCost]=useState(data?.cookingPlan?.homeCookBudget||80);const [deposit,setDeposit]=useState(estimate);const [vegetables,setVegetables]=useState(true);const [lowOil,setLowOil]=useState(true);const finish=async()=>{await api('/cooking/outcomes',json('POST',{completionKey:crypto.randomUUID(),recipe,ingredientIds,homeCookCost:cost,actualDeposit:deposit,foodSafe:true,vegetables,lowOil,mindfulSeasoning:true}));await query.invalidateQueries({queryKey:stateQueryKey});onComplete?.();onClose();ui.toast(`料理完成，實際計入目標 NT$ ${deposit}`)};return <Modal label="料理完成結算" onClose={onClose}><ModalHeader title={recipe.title} kicker="料理已完成" onClose={onClose}/><div className="grid grid-cols-2 gap-sm"><div className="rounded-2xl bg-surface-container-low p-md"><span className="text-[10px] text-outline">原本平均外食</span><strong className="block text-lg text-slate-blue">NT$ {data?.cookingPlan?.eatingOutCost||0}</strong></div><label className="rounded-2xl bg-surface-container-low p-md text-[10px] text-outline">本餐自煮成本<input className="field" type="number" min="0" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label></div><div className="mt-sm rounded-2xl bg-secondary/10 p-md"><span className="text-[10px] text-on-surface-variant">本餐估算節省</span><strong className="block text-2xl text-secondary">NT$ {Math.max(0,(data?.cookingPlan?.eatingOutCost||0)-cost)}</strong><p className="text-[10px] text-outline">這是估算，不會自動加入主要目標。</p></div><label className="mt-md block text-xs font-bold text-on-surface-variant">這次實際計入目標多少<input className="field" type="number" min="0" value={deposit} onChange={e=>setDeposit(Number(e.target.value))}/></label><div className="mt-md flex gap-md text-xs font-bold text-on-surface-variant"><label><input type="checkbox" checked={vegetables} onChange={e=>setVegetables(e.target.checked)}/> 有蔬菜</label><label><input type="checkbox" checked={lowOil} onChange={e=>setLowOil(e.target.checked)}/> 低油</label></div><div className="mt-lg flex gap-sm"><button onClick={()=>setDeposit(0)} className="secondary-btn flex-1">這次不計入</button><button onClick={finish} className="primary-btn flex-1">確認計入目標</button></div></Modal>}
