import { useContext, useMemo, useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import type { GoalDraft } from '@coocoo/contracts'
import { calculateAverageEatingOutCost, calculateGoalProjection, suggestHomeCookBudget } from '@coocoo/core'
import { api, json } from '@/shared/api/client'
import { Modal } from '@/shared/ui/Modal'
import { UiContext } from '@/app/ui-context'
import { stateQueryKey } from '@/entities/app-state/model'

const purposes=[['travel','旅行計畫','flight'],['purchase','想買的物品','redeem'],['emergency','緊急預備金','savings'],['health','健康準備','health_and_safety']]
const initial:GoalDraft={purpose:'travel',name:'日本旅行',targetAmount:30000,currentSavedAmount:0,targetDate:null,eatingOutMeals:7,eatingOutTotal:1050,directEatingOutCost:150,homeCookBudget:90,weeklyCookingMeals:3,shortPercent:25,mediumPercent:60,shortLabel:'第一段累積',mediumLabel:'穩定前進',longLabel:'完成主要目標'}

export function GoalSetupModal({onClose}:{onClose:()=>void}){
  const [step,setStep]=useState(1);const [draft,setDraft]=useState(initial);const [error,setError]=useState('');const query=useQueryClient();const ui=useContext(UiContext)
  const baseline=calculateAverageEatingOutCost(draft.eatingOutTotal,draft.eatingOutMeals)??draft.directEatingOutCost??0
  const saving=Math.max(0,baseline-draft.homeCookBudget)
  const projection=useMemo(()=>calculateGoalProjection({targetAmount:draft.targetAmount,currentSavedAmount:draft.currentSavedAmount,estimatedSavingPerMeal:saving,weeklyCookingMeals:draft.weeklyCookingMeals,targetDate:draft.targetDate}),[draft, saving])
  const update=<K extends keyof GoalDraft>(key:K,value:GoalDraft[K])=>setDraft(current=>({...current,[key]:value}))
  const next=()=>{if(step===1&&!draft.name.trim())return setError('請輸入目標名稱。');if(step===2&&draft.targetAmount<=0)return setError('目標金額必須大於 0 元。');setError('');setStep(v=>Math.min(6,v+1))}
  const confirm=async()=>{try{await api('/goals',json('POST',draft));await query.invalidateQueries({queryKey:stateQueryKey});onClose();ui.toast('主要目標與自煮計畫已建立')}catch(e){setError(e instanceof Error?e.message:'建立失敗')}}
  return <Modal label="設定主要目標" onClose={onClose}><div className="mb-lg"><div className="flex items-start justify-between"><div><p className="text-[10px] font-extrabold tracking-[.16em] text-secondary">一個目標，一條清楚的路</p><h2 className="mt-1 text-xl font-extrabold text-slate-blue">{['想完成什麼？','設定目標金額','了解最近外食','安排自煮節奏','三段里程碑','確認起始計畫'][step-1]}</h2></div><button onClick={onClose} aria-label="取消設定" className="rounded-full p-2 text-on-surface-variant hover:bg-surface-container"><span className="material-symbols-outlined">close</span></button></div><div className="mt-md flex gap-xs">{[1,2,3,4,5,6].map(n=><span key={n} className={`h-1.5 flex-1 rounded-full ${n<=step?'bg-primary':'bg-surface-container'}`}/>)}</div></div>
    {step===1&&<div><div className="grid grid-cols-2 gap-sm">{purposes.map(([id,label,icon])=><button key={id} onClick={()=>update('purpose',id)} className={`rounded-2xl border-2 p-md text-left ${draft.purpose===id?'border-primary bg-primary/5':'border-outline-variant/30'}`}><span className="material-symbols-outlined text-primary">{icon}</span><strong className="mt-1 block text-sm text-slate-blue">{label}</strong></button>)}</div><label className="mt-md block text-xs font-bold text-on-surface-variant">目標名稱<input className="field" value={draft.name} onChange={e=>update('name',e.target.value)}/></label></div>}
    {step===2&&<div className="grid grid-cols-1 gap-md sm:grid-cols-2"><label className="text-xs font-bold text-on-surface-variant">目標金額<input className="field" type="number" min="1" value={draft.targetAmount} onChange={e=>update('targetAmount',Number(e.target.value))}/></label><label className="text-xs font-bold text-on-surface-variant">目前已存<input className="field" type="number" min="0" value={draft.currentSavedAmount} onChange={e=>update('currentSavedAmount',Number(e.target.value))}/></label><label className="text-xs font-bold text-on-surface-variant sm:col-span-2">目標日期（選填）<input className="field" type="date" value={draft.targetDate||''} onChange={e=>update('targetDate',e.target.value||null)}/></label></div>}
    {step===3&&<div className="grid grid-cols-1 gap-md sm:grid-cols-2"><label className="text-xs font-bold text-on-surface-variant">最近外食餐數<input className="field" type="number" min="0" value={draft.eatingOutMeals} onChange={e=>update('eatingOutMeals',Number(e.target.value))}/></label><label className="text-xs font-bold text-on-surface-variant">外食總額<input className="field" type="number" min="0" value={draft.eatingOutTotal} onChange={e=>{const total=Number(e.target.value);setDraft(d=>({...d,eatingOutTotal:total,homeCookBudget:suggestHomeCookBudget(calculateAverageEatingOutCost(total,d.eatingOutMeals)??d.directEatingOutCost)}))}}/></label>{draft.eatingOutMeals===0&&<label className="text-xs font-bold text-on-surface-variant sm:col-span-2">平均一餐外食<input className="field" type="number" value={draft.directEatingOutCost} onChange={e=>update('directEatingOutCost',Number(e.target.value))}/></label>}<div className="rounded-2xl bg-surface-container-low p-md text-sm text-slate-blue sm:col-span-2">目前平均每餐外食約 <strong>NT$ {baseline}</strong></div></div>}
    {step===4&&<div className="grid grid-cols-1 gap-md sm:grid-cols-2"><label className="text-xs font-bold text-on-surface-variant">每餐自煮預算<input className="field" type="number" min="0" value={draft.homeCookBudget} onChange={e=>update('homeCookBudget',Number(e.target.value))}/></label><label className="text-xs font-bold text-on-surface-variant">每週預計自煮餐數<input className="field" type="number" min="0" max="21" value={draft.weeklyCookingMeals} onChange={e=>update('weeklyCookingMeals',Number(e.target.value))}/></label><div className="rounded-2xl bg-secondary/10 p-md sm:col-span-2"><span className="text-[10px] text-on-surface-variant">每餐估算節省</span><strong className="mt-1 block text-2xl text-secondary">NT$ {saving}</strong></div></div>}
    {step===5&&<div className="space-y-sm">{[[25,draft.shortLabel],[60,draft.mediumLabel],[100,draft.longLabel]].map(([percent,label])=><div key={String(percent)} className="rounded-2xl border border-outline-variant/30 bg-surface-container-low p-md"><span className="text-[10px] font-extrabold text-secondary">{percent}%</span><strong className="ml-2 text-sm text-slate-blue">{label}</strong><span className="float-right text-xs font-extrabold text-primary">NT$ {Math.round(draft.targetAmount*Number(percent)/100).toLocaleString()}</span></div>)}</div>}
    {step===6&&<div className="space-y-md"><div className="rounded-3xl border border-primary/10 bg-surface-container-low p-lg"><p className="text-[10px] font-extrabold text-secondary">主要目標</p><h3 className="mt-1 text-xl font-extrabold text-slate-blue">{draft.name}</h3><div className="mt-md grid grid-cols-2 gap-sm text-center"><div><span className="block text-[10px] text-outline">還差</span><strong className="text-primary">NT$ {projection.remainingAmount.toLocaleString()}</strong></div><div><span className="block text-[10px] text-outline">約需</span><strong className="text-secondary">{projection.mealsNeeded??'—'} 餐</strong></div></div><p className="mt-md text-center text-xs text-on-surface-variant">每週 {draft.weeklyCookingMeals} 餐，預估 {projection.estimatedDate||'依實際節奏調整'} 完成</p></div></div>}
    {error&&<p role="alert" className="mt-md rounded-xl bg-error-container px-md py-sm text-xs font-bold text-on-error-container">{error}</p>}
    <div className="mt-lg flex justify-between gap-sm">{step>1?<button className="secondary-btn" onClick={()=>setStep(v=>v-1)}>上一步</button>:<span/>}<button className="primary-btn" onClick={step===6?confirm:next}>{step===6?'採用這個計畫':'下一步'}</button></div>
  </Modal>
}
