import { useContext, useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { calculateCurrentSaved } from '@coocoo/core'
import { useAppState, stateQueryKey } from '@/entities/app-state/model'
import { api, json } from '@/shared/api/client'
import { Modal, ModalHeader } from '@/shared/ui/Modal'
import { UiContext } from '@/app/ui-context'

export function GoalSettingsModal({onClose}:{onClose:()=>void}){const {data}=useAppState();const ui=useContext(UiContext);const query=useQueryClient();const goal=data!.activeGoal!;const plan=data!.cookingPlan!;const [target,setTarget]=useState(goal.targetAmount);const [saved,setSaved]=useState(calculateCurrentSaved(data!.amountEvents.filter(e=>e.goalId===goal.id)));const [budget,setBudget]=useState(plan.homeCookBudget);const [weekly,setWeekly]=useState(plan.weeklyCookingMeals);const save=async()=>{await api(`/goals/${goal.id}`,json('PATCH',{targetAmount:target,desiredSaved:saved,homeCookBudget:budget,weeklyCookingMeals:weekly}));await query.invalidateQueries({queryKey:stateQueryKey});onClose();ui.toast('目標與自煮計畫已更新')};return <Modal label="調整主要目標" onClose={onClose}><ModalHeader title="主要目標與自煮計畫" kicker="隨生活調整" onClose={onClose}/><div className="grid grid-cols-1 gap-md sm:grid-cols-2"><label className="text-xs font-bold text-on-surface-variant">目標金額<input className="field" type="number" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><label className="text-xs font-bold text-on-surface-variant">目前已存<input className="field" type="number" value={saved} onChange={e=>setSaved(Number(e.target.value))}/><span className="mt-1 block text-[10px] font-normal text-outline">修正會保存成一筆差額紀錄。</span></label><label className="text-xs font-bold text-on-surface-variant">每餐自煮預算<input className="field" type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label className="text-xs font-bold text-on-surface-variant">每週預計自煮餐數<input className="field" type="number" min="0" max="21" value={weekly} onChange={e=>setWeekly(Number(e.target.value))}/></label></div><div className="mt-lg flex gap-sm"><button onClick={onClose} className="secondary-btn flex-1">取消</button><button onClick={save} className="primary-btn flex-1">儲存調整</button></div></Modal>}
