import { useContext } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { UiContext } from '@/app/ui-context'
import { Modal, ModalHeader } from '@/shared/ui/Modal'
import { api, json } from '@/shared/api/client'
import { stateQueryKey } from '@/entities/app-state/model'

export function AddInventoryModal({onClose}:{onClose:()=>void}){const ui=useContext(UiContext);const query=useQueryClient();return <Modal label="新增食材" onClose={onClose}><ModalHeader title="新增冰箱食材" onClose={onClose}/><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/inventory',json('POST',{name:String(f.get('name')),chamber:String(f.get('chamber')),qty:Number(f.get('qty')),unit:String(f.get('unit')),daysLeft:Number(f.get('daysLeft')),image:'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=500&q=80',addedDate:new Date().toISOString().slice(0,10),roi:{savings:50,sodium:100,fat:5},storageProtocol:'方形收納管理：先進先出，定期檢查保鮮期。',boxSize:'M'}));await query.invalidateQueries({queryKey:stateQueryKey});onClose();ui.toast('食材已加入冰箱')}} className="grid grid-cols-2 gap-md"><label className="col-span-2 text-xs font-bold text-on-surface-variant">食材名稱<input className="field" name="name" required placeholder="例如：空心菜"/></label><label className="text-xs font-bold text-on-surface-variant">存放區<select className="field" name="chamber"><option value="cold">冷藏室</option><option value="frozen">冷凍庫</option></select></label><label className="text-xs font-bold text-on-surface-variant">剩餘天數<input className="field" name="daysLeft" type="number" defaultValue="7" min="0"/></label><label className="text-xs font-bold text-on-surface-variant">數量<input className="field" name="qty" type="number" defaultValue="1" min="0"/></label><label className="text-xs font-bold text-on-surface-variant">單位<input className="field" name="unit" defaultValue="包"/></label><div className="col-span-2 mt-md flex gap-sm"><button type="button" onClick={onClose} className="secondary-btn flex-1">取消</button><button className="primary-btn flex-1">確認加入</button></div></form></Modal>}
export function FridgeSetupModal({onClose}:{onClose:()=>void}){const ui=useContext(UiContext);const query=useQueryClient();return <Modal label="設定我的冰箱" onClose={onClose}><ModalHeader title="設定我的冰箱" onClose={onClose}/><div className="mb-md flex rounded-xl bg-surface-container p-1"><button className="flex-1 rounded-xl bg-slate-blue px-2 py-2 text-xs font-bold text-white">廠牌型號</button><button className="flex-1 px-2 py-2 text-xs font-bold text-outline">拍照辨識</button><button className="flex-1 px-2 py-2 text-xs font-bold text-outline">手動輸入</button></div><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/settings/fridge',json('PUT',{brand:String(f.get('brand')),model:String(f.get('model')),capacityLiters:470,coldRatio:.55,isConfigured:true}));await query.invalidateQueries({queryKey:stateQueryKey});onClose();ui.toast('冰箱設定完成！')}}><label className="text-xs font-bold text-slate-blue">品牌<select name="brand" className="field"><option>Panasonic</option><option>Hitachi</option><option>Toshiba</option></select></label><label className="mt-md block text-xs font-bold text-slate-blue">型號<select name="model" className="field"><option>NR-C470 (470L 三門)</option><option>NR-B239 (232L 雙門)</option></select></label><button className="primary-btn mt-lg w-full">完成設定</button></form></Modal>}
