import { useContext } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { UiContext } from '@/app/ui-context'
import { Modal, ModalHeader } from '@/shared/ui/Modal'
import { api, json } from '@/shared/api/client'
import { stateQueryKey } from '@/entities/app-state/model'

export function AddInventoryModal({onClose}:{onClose:()=>void}){const ui=useContext(UiContext);const query=useQueryClient();return <Modal label="新增食材" onClose={onClose}><ModalHeader title="新增精確食材" kicker="數量、位置與期限都會影響推薦" onClose={onClose}/><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')),expiresOn=String(f.get('expiresOn')),daysLeft=Math.max(0,Math.ceil((new Date(`${expiresOn}T00:00:00`).getTime()-Date.now())/86400000));await api('/inventory',json('POST',{ingredientKey:name,name,chamber:String(f.get('chamber')),qty:Number(f.get('qty')),unit:String(f.get('unit')),daysLeft,expiresOn,lastConfirmedAt:new Date().toISOString(),image:'/favicon.svg',addedDate:new Date().toISOString().slice(0,10),estimatedValue:0,storageProtocol:'先進先出，使用前依期限確認。',boxSize:'M'}));await query.invalidateQueries({queryKey:stateQueryKey});onClose();ui.toast('食材已加入精確冰箱')}} className="grid grid-cols-2 gap-md"><label className="col-span-2 text-xs font-bold text-on-surface-variant">食材名稱<input className="field" name="name" required placeholder="例如：空心菜"/></label><label className="text-xs font-bold text-on-surface-variant">存放區<select className="field" name="chamber"><option value="cold">冷藏室</option><option value="frozen">冷凍庫</option><option value="pantry">常溫</option></select></label><label className="text-xs font-bold text-on-surface-variant">期限<input className="field" name="expiresOn" type="date" required/></label><label className="text-xs font-bold text-on-surface-variant">數量<input className="field" name="qty" type="number" defaultValue="1" min="0.01" step="0.01" required/></label><label className="text-xs font-bold text-on-surface-variant">單位<input className="field" name="unit" defaultValue="包" required/></label><div className="col-span-2 mt-md flex gap-sm"><button type="button" onClick={onClose} className="secondary-btn flex-1">取消</button><button className="primary-btn flex-1">確認加入</button></div></form></Modal>}
export function FridgeSetupModal({onClose}:{onClose:()=>void}){const ui=useContext(UiContext);const query=useQueryClient();return <Modal label="設定我的冰箱" onClose={onClose}><ModalHeader title="設定我的冰箱" onClose={onClose}/><div className="mb-md flex rounded-xl bg-surface-container p-1"><button className="flex-1 rounded-xl bg-slate-blue px-2 py-2 text-xs font-bold text-white">廠牌型號</button><button className="flex-1 px-2 py-2 text-xs font-bold text-outline">拍照辨識</button><button className="flex-1 px-2 py-2 text-xs font-bold text-outline">手動輸入</button></div><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/settings/fridge',json('PUT',{brand:String(f.get('brand')),model:String(f.get('model')),capacityLiters:470,coldRatio:.55,isConfigured:true}));await query.invalidateQueries({queryKey:stateQueryKey});onClose();ui.toast('冰箱設定完成！')}}><label className="text-xs font-bold text-slate-blue">品牌<select name="brand" className="field"><option>Panasonic</option><option>Hitachi</option><option>Toshiba</option></select></label><label className="mt-md block text-xs font-bold text-slate-blue">型號<select name="model" className="field"><option>NR-C470 (470L 三門)</option><option>NR-B239 (232L 雙門)</option></select></label><button className="primary-btn mt-lg w-full">完成設定</button></form></Modal>}
