import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { CatalogAdminState, IngredientPrice } from '@coocoo/contracts';
import { api, json } from '@/shared/api/client';
import { Modal, ModalHeader } from '@/shared/ui/Modal';
export function CatalogAdminModal({onClose}:{onClose:()=>void}){
 const q=useQuery({queryKey:['catalog-admin'],queryFn:()=>api<CatalogAdminState>('/admin/recipes')});const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [priceId,setPriceId]=useState<string|null>(null);
 const [price,setPrice]=useState({ingredientKey:'',name:'',packageQuantity:1,unit:'克',price:0,source:'',observedAt:new Date().toISOString().slice(0,10)});
 const act=async(path:string,body:unknown,method='POST')=>{setBusy(true);setError('');try{await api(path,json(method,body));await q.refetch();}catch(e){setError(e instanceof Error?e.message:'操作失敗');}finally{setBusy(false);}};
 return <Modal label="食譜管理" onClose={onClose} wide><ModalHeader title="食譜與自動更新管理" onClose={onClose}/>{q.error&&<p role="alert">無法載入，請確認管理者權限與資料庫版本。</p>}{q.data&&<div className="space-y-md"><p>本月候選 {q.data.candidateCount}/50 · 已計費估算 NT${q.data.spentTwd.toFixed(2)} · 預留 NT${q.data.reservedTwd.toFixed(2)} / 月額度 300</p><p className="text-xs">最近排程回報：{q.data.lastRunAt||'尚未執行'}。無回報不能視為自動更新已啟用。</p>{q.data.alerts.map(x=><p key={x} className="text-error">{x}</p>)}<button className="primary-btn" disabled={busy} onClick={()=>void act('/admin/recipes/control',{paused:!q.data!.paused},'PUT')}>{q.data.paused?'啟用已部署的排程':'暫停新增生成'}</button>
 <details><summary>食材參考價格（{q.data.prices.length} 筆）</summary><p className="text-xs my-sm">填入可追溯的實際參考資料；來源必須是 https 網址或以 receipt: 開頭的憑證說明，超過 30 天列為待更新。</p>{(['ingredientKey','name','unit','source','observedAt'] as const).map(key=><label className="field-label" key={key}>{({ingredientKey:'食材識別名稱',name:'顯示名稱',unit:'包裝內容單位',source:'來源網址或 receipt: 憑證說明',observedAt:'查價日期'})[key]}<input className="field" type={key==='observedAt'?'date':'text'} value={price[key]} onChange={e=>setPrice({...price,[key]:e.target.value})}/></label>)}<label className="field-label">每包裝內容量<input className="field" type="number" min="0.001" value={price.packageQuantity} onChange={e=>setPrice({...price,packageQuantity:Number(e.target.value)})}/></label><label className="field-label">每包裝參考價 NT$<input className="field" type="number" min="0" value={price.price} onChange={e=>setPrice({...price,price:Number(e.target.value)})}/></label><button className="secondary-btn" disabled={busy} onClick={()=>void act('/admin/recipes/prices',{...price,id:priceId||crypto.randomUUID(),observedAt:price.observedAt+'T00:00:00+08:00'} satisfies IngredientPrice,'PUT')}>新增參考價格</button>{q.data.prices.map(p=><div key={p.id} className="text-xs my-sm">{p.name} · {p.packageQuantity}{p.unit} / NT${p.price} · {p.observedAt.slice(0,10)}<button className="secondary-btn" onClick={()=>{setPriceId(p.id);setPrice({...p,observedAt:p.observedAt.slice(0,10)});}}>帶入修訂</button></div>)}</details>
 <details><summary>使用者回報（{q.data.reports.length} 筆）</summary>{q.data.reports.map(report=><article key={report.id} className="rounded-2xl bg-surface-container-low p-md my-sm"><strong>{report.safety?'食安回報':'品質回報'} · {report.title}</strong><p className="text-xs">{report.message}</p><small>{report.createdAt} · {report.processedAt?'已觸發處理':'累積門檻中'}</small></article>)}</details>
 <div>{q.data.versions.map(v=><article key={v.id} className="rounded-2xl bg-surface-container-low p-md my-sm"><strong>{v.recipe.title}</strong><p className="text-xs">{({candidate:'候選',published:'已發布',quarantined:'隔離待審',rejected:'未通過'})[v.status]} · {v.createdAt}</p><p className="text-xs">{v.reasons.join('、')}</p><details><summary>查看此版本</summary><pre className="whitespace-pre-wrap text-xs">{JSON.stringify(v.recipe,null,2)}</pre></details><button className="secondary-btn" disabled={busy||v.status==='quarantined'} onClick={()=>void act(`/admin/recipes/${v.id}/quarantine`,{reason:'管理者暫停推薦'})}>暫停推薦</button>{v.status!=='published'&&<button className="secondary-btn" disabled={busy} onClick={()=>void act(`/admin/recipes/${v.id}/review`,{})}>建立修訂並重新品檢</button>}</article>)}</div></div>}{error&&<p role="alert" className="text-error">{error}</p>}</Modal>;
}
